#########################################################
### List contents of the chain
#########################################################
GET http://localhost:8080/chain


#########################################################
### Add a MINED block to the chain
#########################################################
# @name addTransaction
POST http://localhost:8080/block

{
  "timestamp": "2022-07-25T13:44:39.782598643Z",
  "data": "{\"Sender\":\"Jim Morrison\",\"Recipient\":\"Tony Iommi\",\"Amount\":34.66}",
  "hash": "000009168a4b4ab06b2adb580d934a66f6c521422be501e49ecde27302506f2d",
  "nonce": 538319,
  "previousHash": "fffffff"
}

@hash = {{addTransaction.response.body.Hash}}


#########################################################
### Get a block
#########################################################
GET http://localhost:8080/block/{{hash}}


#########################################################
### Tamper with the data of a given block
#########################################################
PUT http://localhost:8080/block/tamper/000009168a4b4ab06b2adb580d934a66f6c521422be501e49ecde27302506f2d


#########################################################
### Check single block integrity
#########################################################
GET http://localhost:8080/block/validate/{{hash}}


#########################################################
### Check whole chain integrity
#########################################################
GET http://localhost:8080/chain/validate
