### List contents of the chain

GET http://localhost:8080/list

### Add a transaction to the chain

POST http://localhost:8080/add

{
  "sender": "David Bowie",
  "recipient": "Lou Reed",
  "amount": 34.77
}